---
- name: Install C# tools on Linux or macOS
  ansible.builtin.command:
    argv:
      - "{{ dotnet_root }}/dotnet"
      - tool
      - install
      - --global
      - "{{ csharp_tool }}"
  loop: "{{ dev_language.tools | default(default_csharp_tools) }}"
  loop_control:
    loop_var: csharp_tool
    label: "{{ csharp_tool }}"
  environment:
    DOTNET_ROOT: "{{ dotnet_root }}"
    PATH: "{{ dotnet_root }}:{{ ansible_env.HOME }}/.dotnet/tools:{{ ansible_env.PATH }}"
  when: ansible_system in ['Linux', 'Darwin']
  changed_when: true

- name: Install C# tools on Windows
  ansible.windows.win_command:
    argv:
      - dotnet.exe
      - tool
      - install
      - --global
      - "{{ csharp_tool }}"
  loop: "{{ dev_language.tools | default(default_csharp_tools) }}"
  loop_control:
    loop_var: csharp_tool
    label: "{{ csharp_tool }}"
  when: ansible_system == 'Windows'
  changed_when: true