---
- name: Install JavaScript tools on Linux or macOS
  ansible.builtin.command:
    argv:
      - "{{ node_install_dir }}/bin/npm"
      - install
      - --global
      - "{{ javascript_tool }}"
  loop: "{{ dev_language.tools | default(default_javascript_tools) }}"
  loop_control:
    loop_var: javascript_tool
    label: "{{ javascript_tool }}"
  environment:
    PATH: "{{ node_install_dir }}/bin:{{ ansible_env.PATH }}"
  when:
    - ansible_system in ['Linux', 'Darwin']
    - javascript_tool != 'npm'
  changed_when: true

- name: Install JavaScript tools on Windows
  ansible.windows.win_command:
    argv:
      - "{{ node_install_dir }}\\npm.cmd"
      - install
      - --global
      - "{{ javascript_tool }}"
  loop: "{{ dev_language.tools | default(default_javascript_tools) }}"
  loop_control:
    loop_var: javascript_tool
    label: "{{ javascript_tool }}"
  when:
    - ansible_system == 'Windows'
    - javascript_tool != 'npm'
  changed_when: true