---
python_build_dependencies:
  - build-base
  - openssl-dev
  - zlib-dev
  - bzip2-dev
  - readline-dev
  - sqlite-dev
  - tk-dev
  - libffi-dev
  - xz-dev
  - git
  - curl

c_compiler_packages:
  - build-base

c_tool_packages:
  build:
    - cmake
    - ninja
  format:
    - clang-extra-tools
  lint:
    - clang-extra-tools
  pkg_config:
    - pkgconf
