---
python_build_dependencies:
  - base-devel
  - openssl
  - zlib
  - bzip2
  - readline
  - sqlite
  - tk
  - libffi
  - xz
  - git
  - curl

c_compiler_packages:
  - base-devel

c_tool_packages:
  build:
    - cmake
    - ninja
  format:
    - clang
  lint:
    - clang
  pkg_config:
    - pkgconf
  language_server:
    - clang
  debugger:
    - gdb
  cache:
    - ccache
