---
python_build_dependencies:
  - gcc
  - gcc-c++
  - make
  - openssl-devel
  - zlib-devel
  - bzip2
  - bzip2-devel
  - readline-devel
  - sqlite
  - sqlite-devel
  - tk-devel
  - libffi-devel
  - xz-devel
  - git
  - curl

c_compiler_packages:
  - gcc
  - gcc-c++
  - make

c_tool_packages:
  build:
    - cmake
    - ninja-build
  format:
    - clang-tools-extra
  lint:
    - clang-tools-extra
  pkg_config:
    - pkgconf-pkg-config
