---
python_build_dependencies:
  - gcc
  - make
  - zlib-devel
  - libbz2-devel
  - libopenssl-devel
  - readline-devel
  - sqlite3-devel
  - tk-devel
  - libffi-devel
  - xz-devel
  - git
  - curl

c_compiler_packages:
  - gcc
  - gcc-c++
  - make

c_tool_packages:
  build:
    - cmake
    - ninja
  format:
    - clang-tools
  lint:
    - clang-tools
  pkg_config:
    - pkg-config
  language_server:
    - clang-tools
  debugger:
    - gdb
  cache:
    - ccache
